// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using idleGood_WebAPI.Models;

#nullable disable

namespace idleGood_WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240313030018_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("AdDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("SellerIconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("SellerId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemId = 100,
                            Description = "This is a description for item 1",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item1.jpg\"]",
                            IsPublic = false,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "2",
                            SellerName = "user2",
                            Title = "Item 1"
                        },
                        new
                        {
                            ItemId = 101,
                            Description = "This is a description for item 2",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item2.jpg\"]",
                            IsPublic = false,
                            LikesCount = 20,
                            Price = 50f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "2",
                            SellerName = "user2",
                            Title = "Item 2"
                        },
                        new
                        {
                            ItemId = 102,
                            Description = "This is a description for item 3",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item3.jpg\"]",
                            IsPublic = true,
                            LikesCount = 120,
                            Price = 20f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon1.jpg",
                            SellerId = "1",
                            SellerName = "User1",
                            Title = "Item 3",
                            VideoUrl = "[\"https://idlegoodstorage.blob.core.windows.net/video/video1.mp4\"]"
                        },
                        new
                        {
                            ItemId = 103,
                            Description = "This is a description for item 4",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item4.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "2",
                            SellerName = "User2",
                            Title = "Item 4"
                        },
                        new
                        {
                            ItemId = 104,
                            Description = "This is a description for item 5",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item5.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "2",
                            SellerName = "User2",
                            Title = "Item 5"
                        },
                        new
                        {
                            ItemId = 105,
                            Description = "This is a description for item 6",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item6.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "2",
                            SellerName = "User2",
                            Title = "Item 6"
                        },
                        new
                        {
                            ItemId = 106,
                            Description = "This is a description for item 7",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item7.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon1.jpg",
                            SellerId = "1",
                            SellerName = "User1",
                            Title = "Item 7"
                        },
                        new
                        {
                            ItemId = 107,
                            Description = "This is a description for item 8",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item8.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon1.jpg",
                            SellerId = "1",
                            SellerName = "User1",
                            Title = "Item 8"
                        },
                        new
                        {
                            ItemId = 108,
                            Description = "This is a description for item 9",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item9.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "2",
                            SellerName = "User2",
                            Title = "Item 9"
                        },
                        new
                        {
                            ItemId = 109,
                            Description = "This is a description for item 10",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item10.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "2",
                            SellerName = "User2",
                            Title = "Item 10"
                        },
                        new
                        {
                            ItemId = 110,
                            Description = "This is a description for item 11",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item11.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon1.jpg",
                            SellerId = "1",
                            SellerName = "User1",
                            Title = "Item 11"
                        },
                        new
                        {
                            ItemId = 111,
                            Description = "This is a description for item 12",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item12.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon1.jpg",
                            SellerId = "1",
                            SellerName = "User1",
                            Title = "Item 12"
                        },
                        new
                        {
                            ItemId = 112,
                            Description = "This is a description for item 13",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item13.jpg\"]",
                            IsPublic = false,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "1",
                            SellerName = "User1",
                            Title = "Item 13"
                        },
                        new
                        {
                            ItemId = 113,
                            Description = "This is a description for item 14",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item14.jpg\"]",
                            IsPublic = false,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "1",
                            SellerName = "User2",
                            Title = "Item 14"
                        },
                        new
                        {
                            ItemId = 114,
                            Description = "This is a description for item 15",
                            ImageUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item15.jpg\"]",
                            IsPublic = true,
                            LikesCount = 10,
                            Price = 10f,
                            SellerIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            SellerId = "2",
                            SellerName = "User2",
                            Title = "Item 15"
                        });
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.ItemTag", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemTag");
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.TransactionHistory", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId1")
                        .HasColumnType("int");

                    b.Property<string>("ItemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId1");

                    b.HasIndex("SellerId");

                    b.ToTable("TransactionHistory");

                    b.HasData(
                        new
                        {
                            TransactionId = 10000,
                            BuyerId = "1",
                            BuyerName = "User1",
                            ItemId = 100,
                            ItemUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item1.jpg\"]",
                            SellerId = "2",
                            SellerName = "User2",
                            Status = "In Progress",
                            TransactionDate = new DateTime(2024, 3, 3, 3, 0, 18, 496, DateTimeKind.Utc).AddTicks(243)
                        },
                        new
                        {
                            TransactionId = 10001,
                            BuyerId = "1",
                            BuyerName = "User1",
                            ItemId = 101,
                            ItemUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item2.jpg\"]",
                            SellerId = "2",
                            SellerName = "User2",
                            Status = "Completed",
                            TransactionDate = new DateTime(2024, 3, 8, 3, 0, 18, 496, DateTimeKind.Utc).AddTicks(252)
                        },
                        new
                        {
                            TransactionId = 10002,
                            BuyerId = "2",
                            BuyerName = "User2",
                            ItemId = 112,
                            ItemUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item13.jpg\"]",
                            SellerId = "1",
                            SellerName = "User1",
                            Status = "In Progress",
                            TransactionDate = new DateTime(2024, 3, 10, 3, 0, 18, 496, DateTimeKind.Utc).AddTicks(255)
                        },
                        new
                        {
                            TransactionId = 10003,
                            BuyerId = "2",
                            BuyerName = "User2",
                            ItemId = 113,
                            ItemUrl = "[\"https://idlegoodstorage.blob.core.windows.net/image/item14.jpg\"]",
                            SellerId = "1",
                            SellerName = "User1",
                            Status = "Completed",
                            TransactionDate = new DateTime(2024, 3, 10, 3, 0, 18, 496, DateTimeKind.Utc).AddTicks(257)
                        });
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfIntro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserIconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Address = "User1 Address",
                            ConcurrencyStamp = "01043a96-be65-4d5a-b00e-952fb64f5a3d",
                            Email = "user1@coventry.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@COVENTRY.COM",
                            NormalizedUserName = "USER1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fa6fb13e-1403-41c8-a7d5-75bf50ed2762",
                            SelfIntro = "Hi, I'm User1",
                            TwoFactorEnabled = false,
                            UserIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon1.jpg",
                            UserName = "User1"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Address = "User2 Address",
                            ConcurrencyStamp = "8f2cd520-d783-4ad2-9726-d77b3b580f28",
                            Email = "user2@coventry.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@COVENTRY.COM",
                            NormalizedUserName = "USER2",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7cf0fda1-6bbe-441f-be5a-ce3794e1a28d",
                            SelfIntro = "Hi, I'm User2",
                            TwoFactorEnabled = false,
                            UserIconUrl = "https://idlegoodstorage.blob.core.windows.net/usericon/icon2.jpg",
                            UserName = "User2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("idleGood_WebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("idleGood_WebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("idleGood_WebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("idleGood_WebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.Item", b =>
                {
                    b.HasOne("idleGood_WebAPI.Models.User", "Seller")
                        .WithMany("ItemsForSale")
                        .HasForeignKey("SellerId");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.ItemTag", b =>
                {
                    b.HasOne("idleGood_WebAPI.Models.Item", "Item")
                        .WithMany("ItemTags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("idleGood_WebAPI.Models.Tag", "Tag")
                        .WithMany("ItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.TransactionHistory", b =>
                {
                    b.HasOne("idleGood_WebAPI.Models.User", "Buyer")
                        .WithMany("Purchases")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("idleGood_WebAPI.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("idleGood_WebAPI.Models.Item", null)
                        .WithMany("TransactionHistory")
                        .HasForeignKey("ItemId1");

                    b.HasOne("idleGood_WebAPI.Models.User", "Seller")
                        .WithMany("Sales")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Buyer");

                    b.Navigation("Item");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.Item", b =>
                {
                    b.Navigation("ItemTags");

                    b.Navigation("TransactionHistory");
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.Tag", b =>
                {
                    b.Navigation("ItemTags");
                });

            modelBuilder.Entity("idleGood_WebAPI.Models.User", b =>
                {
                    b.Navigation("ItemsForSale");

                    b.Navigation("Purchases");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
